[package]
name = "tg-join-leave-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
telegram-bot = { version = "0.9.0", git = "https://github.com/telegram-rs/telegram-bot.git" }
tokio = { version = "1.17.0", features = [ "macros", "rt", "rt-multi-thread" ] }
